---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 62.84.122.255
    jenkins-agent-01:
      ansible_host: 62.84.123.93
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: netology