{
 "title": "Netology",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((rate(node_cpu_seconds_total{cpu=\"0\",job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "cpu_0"
    },
    {
     "expr": "100 - ((rate(node_cpu_seconds_total{cpu=\"1\",job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "cpu_1"
    },
    {
     "expr": "100 - ((rate(node_cpu_seconds_total{cpu=\"2\",job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "cpu_2"
    },
    {
     "expr": "100 - ((rate(node_cpu_seconds_total{cpu=\"3\",job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "cpu_3"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[5m]) + avg_over_time(node_memory_Cached_bytes[5m]) + avg_over_time(node_memory_Buffers_bytes[5m])) / avg_over_time(node_memory_MemTotal_bytes[5m])))",
     "legendFormat": "free_mem_instance"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node\",cpu=\"0\",mode=\"idle\"}[1m])*100",
     "legendFormat": "node_cpu_0"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node\",cpu=\"1\",mode=\"idle\"}[1m])*100",
     "legendFormat": "node_cpu_1"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node\",cpu=\"2\",mode=\"idle\"}[1m])*100",
     "legendFormat": "node_cpu_2"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"node\",cpu=\"3\",mode=\"idle\"}[1m])*100",
     "legendFormat": "node_cpu_3"
    }
   ]
  },
  {
   "title": "FileSystem Availabel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"})*100",
     "legendFormat": "fs_free"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 } }
 ]
}